Here's the fixed version with the missing closing brackets and proper formatting:

```typescript
// ... [previous code remains the same until the button onClick handlers]

                    onClick={() => {
                      if (selectedTemplateId && formData.studentName) {
                        const currentTemplateObject = fullTemplatesData.find(t => t.id === selectedTemplateId);
                        if (currentTemplateObject) {
                          const reportText = populateTemplate(currentTemplateObject.content, formData);
                          
                          const newReportToAdd: Report = {
                            // id will be generated by addReport in context
                            id: 0, // Temporary, will be overwritten
                            name: `${formData.studentName} - ${currentTemplateObject.name}`,
                            type: currentTemplateObject.name, // Or selectedTemplateId for a more programmatic type
                            date: new Date().toISOString().split('T')[0], // Today's date
                            status: 'Completed', // Or 'Draft' if you prefer
                            content: reportText,
                            formData: { ...formData } // Store a copy of the form data
                          };
                          
                          addReport(newReportToAdd);
                          navigate('/reports'); // Navigate back to the reports list
                        } else {
                          alert("Error: Could not find template information to save the report.");
                        }
                      } else {
                        alert("Error: Student name and template are required to save the report.");
                      }
                    }}
                    className="btn bg-accent-gold text-black"
                  >
                    Generate Final Report
                  </button>
                </div>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default CreateReportPage;
```

The main fixes were:
1. Removed duplicate button onClick handler
2. Added missing closing bracket for button element
3. Added proper closing tags for nested div elements
4. Ensured proper indentation and formatting